; extends
; Generated by scripts/generate.js. Do not edit.

; Attribute expressions, not plain signal names or preserved-attribute lists.
((attribute
  (attribute_name) @_attr
  (quoted_attribute_value
    (attribute_value) @injection.content))
  (#match? @_attr "^data-(star-)?(attr|class|computed|effect|init|json-signals|on|on-intersect|on-interval|on-signal-patch|on-signal-patch-filter|show|signals|style|text|animate|custom-validity|on-raf|on-resize|persist|query-string|replace-url|scroll-into-view|view-transition|if|else-if|for)(:|__|$)")
  (#set! injection.language "datastar"))

; Media queries may be raw text. Inject only quoted expression values.
((attribute
  (attribute_name) @_attr
  (quoted_attribute_value (attribute_value) @injection.content))
  (#match? @_attr "^data-(star-)?(match-media)(:|__|$)")
  (#match? @injection.content "^[\"'`]")
  (#set! injection.language "datastar"))

; Attribute names, including keys and modifiers.
((attribute_name) @injection.content
  (#match? @injection.content "^data-(star-)?(attr|bind|class|computed|effect|ignore|ignore-morph|indicator|init|json-signals|nonce|on|on-intersect|on-interval|on-signal-patch|on-signal-patch-filter|preserve-attr|ref|show|signals|style|text|animate|custom-validity|match-media|on-raf|on-resize|persist|query-string|replace-url|scroll-into-view|view-transition|if|else-if|else|for)(:|__|$)")
  (#set! injection.language "datastar")
  (#set! injection.include-children))
