; extends
; Generated by scripts/generate.js. Do not edit.

; Quoted expression strings in regular or namespaced attributes.
((jsx_attribute
  [(property_identifier) (jsx_namespace_name)] @_attr
  (string (string_fragment) @injection.content))
  (#match? @_attr "^data-(star-)?(attr|class|computed|effect|init|json-signals|on|on-intersect|on-interval|on-signal-patch|on-signal-patch-filter|show|signals|style|text|animate|custom-validity|on-raf|on-resize|persist|query-string|replace-url|scroll-into-view|view-transition|if|else-if|for)(:|__|$)")
  (#set! injection.language "datastar"))

; Dynamic host templates cannot be reconstructed from isolated fragments.
((jsx_attribute
  [(property_identifier) (jsx_namespace_name)] @_attr
  (jsx_expression
    (template_string (string_fragment) @injection.content) @_template))
  (#match? @_attr "^data-(star-)?(attr|class|computed|effect|init|json-signals|on|on-intersect|on-interval|on-signal-patch|on-signal-patch-filter|show|signals|style|text|animate|custom-validity|on-raf|on-resize|persist|query-string|replace-url|scroll-into-view|view-transition|if|else-if|for)(:|__|$)")
  (#not-match? @_template "[$][{]")
  (#set! injection.language "datastar"))

; Media queries may be raw text. Inject only quoted expression values.
((jsx_attribute
  [(property_identifier) (jsx_namespace_name)] @_attr
  (string (string_fragment) @injection.content))
  (#match? @_attr "^data-(star-)?(match-media)(:|__|$)")
  (#match? @injection.content "^[\"'`]")
  (#set! injection.language "datastar"))

((jsx_attribute
  [(property_identifier) (jsx_namespace_name)] @_attr
  (jsx_expression
    (template_string (string_fragment) @injection.content) @_template))
  (#match? @_attr "^data-(star-)?(match-media)(:|__|$)")
  (#match? @injection.content "^[\"'`]")
  (#not-match? @_template "[$][{]")
  (#set! injection.language "datastar"))

; Only attribute names, not arbitrary JavaScript properties.
((jsx_attribute
  [(property_identifier) (jsx_namespace_name)] @injection.content)
  (#match? @injection.content "^data-(star-)?(attr|bind|class|computed|effect|ignore|ignore-morph|indicator|init|json-signals|nonce|on|on-intersect|on-interval|on-signal-patch|on-signal-patch-filter|preserve-attr|ref|show|signals|style|text|animate|custom-validity|match-media|on-raf|on-resize|persist|query-string|replace-url|scroll-into-view|view-transition|if|else-if|else|for)(:|__|$)")
  (#set! injection.language "datastar")
  (#set! injection.include-children))

; Attribute names in attrs={{ ... }} objects.
((jsx_attribute
  (property_identifier) @_name
  (jsx_expression
    (object
      (pair key: (string (string_fragment) @injection.content)))))
  (#eq? @_name "attrs")
  (#match? @injection.content "^data-(star-)?(attr|bind|class|computed|effect|ignore|ignore-morph|indicator|init|json-signals|nonce|on|on-intersect|on-interval|on-signal-patch|on-signal-patch-filter|preserve-attr|ref|show|signals|style|text|animate|custom-validity|match-media|on-raf|on-resize|persist|query-string|replace-url|scroll-into-view|view-transition|if|else-if|else|for)(:|__|$)")
  (#set! injection.language "datastar"))

; Expression values in attrs={{ ... }} objects.
((jsx_attribute
  (property_identifier) @_name
  (jsx_expression
    (object
      (pair
        key: (string (string_fragment) @_key)
        value: (string (string_fragment) @injection.content)))))
  (#eq? @_name "attrs")
  (#match? @_key "^data-(star-)?(attr|class|computed|effect|init|json-signals|on|on-intersect|on-interval|on-signal-patch|on-signal-patch-filter|show|signals|style|text|animate|custom-validity|on-raf|on-resize|persist|query-string|replace-url|scroll-into-view|view-transition|if|else-if|for)(:|__|$)")
  (#set! injection.language "datastar"))

((jsx_attribute
  (property_identifier) @_name
  (jsx_expression
    (object
      (pair
        key: (string (string_fragment) @_key)
        value: (string (string_fragment) @injection.content)))))
  (#eq? @_name "attrs")
  (#match? @_key "^data-(star-)?(match-media)(:|__|$)")
  (#match? @injection.content "^[\"'`]")
  (#set! injection.language "datastar"))
