// Regenerate bindings, scanner, parser, and editor queries in dependency order.
const { execFileSync } = require("node:child_process");
const { readFileSync, writeFileSync } = require("node:fs");
const { dirname, resolve } = require("node:path");
const upstream = dirname(require.resolve("tree-sitter-javascript/package.json"));
const root = resolve(__dirname, "..");
const readUpstream = (path) => readFileSync(resolve(upstream, path), "utf8");
const version = JSON.parse(readUpstream("package.json")).version;
const check = process.argv.includes("--check");
const output = (path, content) => {
  const destination = resolve(root, path);
  if (check) {
    if (readFileSync(destination, "utf8") !== content) throw new Error(`outdated generated artifact: ${path}`);
  } else {
    writeFileSync(destination, content);
  }
};

// Keep Swift's public header self-contained while sharing the C API definition.
output("bindings/swift/TreeSitterDatastar/datastar.h",
  "/* Generated from bindings/c/tree_sitter/tree-sitter-datastar.h. Do not edit. */\n"
    + readFileSync(resolve(root, "bindings/c/tree_sitter/tree-sitter-datastar.h"), "utf8"));

const scanner = readUpstream("src/scanner.c")
  .replaceAll("tree_sitter_javascript", "tree_sitter_datastar")
  .replace("bool tree_sitter_datastar_external_scanner_scan(", "static bool scan_javascript(")
  .replace("external_scanner_destroy(void *p) {}", "external_scanner_destroy(void *p) { (void)p; }")
  .replace("external_scanner_serialize(void *payload, char *buffer) { return 0; }", "external_scanner_serialize(void *payload, char *buffer) { (void)payload; (void)buffer; return 0; }")
  .replace("external_scanner_deserialize(void *p, const char *b, unsigned n) {}", "external_scanner_deserialize(void *p, const char *b, unsigned n) { (void)p; (void)b; (void)n; }")
  .replace("static bool scan_javascript(void *payload, TSLexer *lexer, const bool *valid_symbols) {", "static bool scan_javascript(void *payload, TSLexer *lexer, const bool *valid_symbols) {\n    (void)payload;");
const policy = `
// Datastar requires statement separators; JavaScript's newline ASI would hide errors.
// Retain implicit termination at EOF and closing braces, including injected ranges.
bool tree_sitter_datastar_external_scanner_scan(void *payload, TSLexer *lexer, const bool *valid_symbols) {
    if (valid_symbols[TEMPLATE_CHARS]) {
        return scan_javascript(payload, lexer, valid_symbols);
    }
    if (valid_symbols[AUTOMATIC_SEMICOLON]) {
        lexer->mark_end(lexer);
        while (iswspace(lexer->lookahead)) {
            skip(lexer);
        }
        if (lexer->eof(lexer) || lexer->lookahead == '}' || lexer->is_at_included_range_start(lexer)) {
            lexer->result_symbol = AUTOMATIC_SEMICOLON;
            return true;
        }
        bool symbols[JSX_TEXT + 1];
        for (unsigned i = 0; i <= JSX_TEXT; i++) {
            symbols[i] = valid_symbols[i];
        }
        symbols[AUTOMATIC_SEMICOLON] = false;
        return scan_javascript(payload, lexer, symbols);
    }
    return scan_javascript(payload, lexer, valid_symbols);
}
`;
output("src/scanner.c", `/* Generated from tree-sitter-javascript ${version}. Do not edit.\n\n${readUpstream("LICENSE")}*/\n\n${scanner}${policy}`);
const datastar = `
; Datastar attribute names, keys, and modifiers.
(datastar_attribute
  ["data-" "data-star-"] @tag.attribute
  (plugin_name) @tag.builtin)
(datastar_attribute ":" @punctuation.delimiter (plugin_key) @property)
(datastar_attribute "__" @punctuation.delimiter)
(modifier (modifier_name) @property)
(modifier "." @punctuation.delimiter (modifier_tag) @property)

; These override generic JavaScript identifier highlighting.
(signal_reference) @variable.builtin.datastar
(action_name) @function.builtin.datastar
["?" ":" "..."] @operator
`;
const highlights = `; Generated by scripts/generate.js from tree-sitter-javascript ${version}. Do not edit.\n`
  + readUpstream("queries/highlights.scm").replace("(regex) @string.special", "(regex) @string.regex") + datastar;
output("queries/datastar/highlights.scm", highlights);

if (!check) {
  execFileSync(process.execPath, [require.resolve("tree-sitter-cli/cli.js"), "generate"], {
    cwd: root,
    stdio: "inherit",
  });
}

// Host injections derive attribute names from the freshly generated grammar.
const grammar = JSON.parse(readFileSync(resolve(root, "src/grammar.json"), "utf8"));
const names = grammar.rules.plugin_name.members.map(({ value }) => value);
const plainValues = new Set([
  "bind", "ignore", "ignore-morph", "indicator", "nonce", "preserve-attr", "ref", "else", "match-media",
]);
const pattern = (plugins) => `^data-(star-)?(${plugins.join("|")})(:|__|$)`;
const attributes = pattern(names);
const expressions = pattern(names.filter((name) => !plainValues.has(name)));
const header = "; Generated by scripts/generate.js. Do not edit.\n";
const media = pattern(["match-media"]);
const quoted = JSON.stringify("^[\"'`]");

const html = `
; Attribute expressions, not plain signal names or preserved-attribute lists.
((attribute
  (attribute_name) @_attr
  (quoted_attribute_value
    (attribute_value) @injection.content))
  (#match? @_attr "${expressions}")
  (#set! injection.language "datastar"))

; Media queries may be raw text. Inject only quoted expression values.
((attribute
  (attribute_name) @_attr
  (quoted_attribute_value (attribute_value) @injection.content))
  (#match? @_attr "${media}")
  (#match? @injection.content ${quoted})
  (#set! injection.language "datastar"))

; Attribute names, including keys and modifiers.
((attribute_name) @injection.content
  (#match? @injection.content "${attributes}")
  (#set! injection.language "datastar")
  (#set! injection.include-children))
`;

const jsx = `
; Quoted expression strings in regular or namespaced attributes.
((jsx_attribute
  [(property_identifier) (jsx_namespace_name)] @_attr
  (string (string_fragment) @injection.content))
  (#match? @_attr "${expressions}")
  (#set! injection.language "datastar"))

; Dynamic host templates cannot be reconstructed from isolated fragments.
((jsx_attribute
  [(property_identifier) (jsx_namespace_name)] @_attr
  (jsx_expression
    (template_string (string_fragment) @injection.content) @_template))
  (#match? @_attr "${expressions}")
  (#not-match? @_template "[$][{]")
  (#set! injection.language "datastar"))

; Media queries may be raw text. Inject only quoted expression values.
((jsx_attribute
  [(property_identifier) (jsx_namespace_name)] @_attr
  (string (string_fragment) @injection.content))
  (#match? @_attr "${media}")
  (#match? @injection.content ${quoted})
  (#set! injection.language "datastar"))

((jsx_attribute
  [(property_identifier) (jsx_namespace_name)] @_attr
  (jsx_expression
    (template_string (string_fragment) @injection.content) @_template))
  (#match? @_attr "${media}")
  (#match? @injection.content ${quoted})
  (#not-match? @_template "[$][{]")
  (#set! injection.language "datastar"))

; Only attribute names, not arbitrary JavaScript properties.
((jsx_attribute
  [(property_identifier) (jsx_namespace_name)] @injection.content)
  (#match? @injection.content "${attributes}")
  (#set! injection.language "datastar")
  (#set! injection.include-children))

; Attribute names in attrs={{ ... }} objects.
((jsx_attribute
  (property_identifier) @_name
  (jsx_expression
    (object
      (pair key: (string (string_fragment) @injection.content)))))
  (#eq? @_name "attrs")
  (#match? @injection.content "${attributes}")
  (#set! injection.language "datastar"))

; Expression values in attrs={{ ... }} objects.
((jsx_attribute
  (property_identifier) @_name
  (jsx_expression
    (object
      (pair
        key: (string (string_fragment) @_key)
        value: (string (string_fragment) @injection.content)))))
  (#eq? @_name "attrs")
  (#match? @_key "${expressions}")
  (#set! injection.language "datastar"))

((jsx_attribute
  (property_identifier) @_name
  (jsx_expression
    (object
      (pair
        key: (string (string_fragment) @_key)
        value: (string (string_fragment) @injection.content)))))
  (#eq? @_name "attrs")
  (#match? @_key "${media}")
  (#match? @injection.content ${quoted})
  (#set! injection.language "datastar"))
`;

for (const language of ["html", "templ", "jsx", "tsx"]) {
  output(
    `after/queries/${language}/injections.scm`,
    `; extends\n${header}${["html", "templ"].includes(language) ? html : jsx}`,
  );
}

// Helix host queries must not combine independent attribute expressions.
const standardHtml = `
((comment) @injection.content
 (#set! injection.language "comment"))

((script_element (raw_text) @injection.content)
 (#set! injection.language "javascript"))

((style_element (raw_text) @injection.content)
 (#set! injection.language "css"))
`;
output("docs/helix-html-injections.scm", header + standardHtml + html);
output("queries/highlights-helix.scm", highlights
  .replaceAll("@variable.builtin.datastar", "@variable.builtin")
  .replaceAll("@function.builtin.datastar", "@function.builtin"));
