// Run after `tree-sitter generate`. Attribute names come from the grammar.
const { readFileSync, writeFileSync } = require("node:fs");
const { resolve } = require("node:path");

const root = resolve(__dirname, "..");
const grammar = JSON.parse(readFileSync(resolve(root, "src/grammar.json"), "utf8"));
const names = grammar.rules.plugin_name.members.map(({ value }) => value);
const plainValues = new Set([
  "bind", "ignore", "ignore-morph", "indicator", "nonce", "preserve-attr", "ref", "else", "match-media",
]);
const pattern = (plugins) => `^data-(star-)?(${plugins.join("|")})(:|__|$)`;
const attributes = pattern(names);
const expressions = pattern(names.filter((name) => !plainValues.has(name)));
const header = "; Generated by scripts/generate-queries.js. Do not edit.\n";
const media = pattern(["match-media"]);
const quoted = JSON.stringify("^[\"'`]");
const output = (path, content) => {
  const destination = resolve(root, path);
  if (process.argv.includes("--check")) {
    if (readFileSync(destination, "utf8") !== content) {
      throw new Error(`outdated generated query: ${path}`);
    }
  } else {
    writeFileSync(destination, content);
  }
};

const html = `
; Attribute expressions, not plain signal names or preserved-attribute lists.
((attribute
  (attribute_name) @_attr
  (quoted_attribute_value
    (attribute_value) @injection.content))
  (#match? @_attr "${expressions}")
  (#set! injection.language "datastar"))

; Media queries may be raw text. Inject only quoted expression values.
((attribute
  (attribute_name) @_attr
  (quoted_attribute_value (attribute_value) @injection.content))
  (#match? @_attr "${media}")
  (#match? @injection.content ${quoted})
  (#set! injection.language "datastar"))

; Attribute names, including keys and modifiers.
((attribute_name) @injection.content
  (#match? @injection.content "${attributes}")
  (#set! injection.language "datastar")
  (#set! injection.include-children))
`;

const jsx = `
; Quoted expression strings in regular or namespaced attributes.
((jsx_attribute
  [(property_identifier) (jsx_namespace_name)] @_attr
  (string (string_fragment) @injection.content))
  (#match? @_attr "${expressions}")
  (#set! injection.language "datastar"))

; Dynamic host templates cannot be reconstructed from isolated fragments.
((jsx_attribute
  [(property_identifier) (jsx_namespace_name)] @_attr
  (jsx_expression
    (template_string (string_fragment) @injection.content) @_template))
  (#match? @_attr "${expressions}")
  (#not-match? @_template "[$][{]")
  (#set! injection.language "datastar"))

; Media queries may be raw text. Inject only quoted expression values.
((jsx_attribute
  [(property_identifier) (jsx_namespace_name)] @_attr
  (string (string_fragment) @injection.content))
  (#match? @_attr "${media}")
  (#match? @injection.content ${quoted})
  (#set! injection.language "datastar"))

((jsx_attribute
  [(property_identifier) (jsx_namespace_name)] @_attr
  (jsx_expression
    (template_string (string_fragment) @injection.content) @_template))
  (#match? @_attr "${media}")
  (#match? @injection.content ${quoted})
  (#not-match? @_template "[$][{]")
  (#set! injection.language "datastar"))

; Only attribute names, not arbitrary JavaScript properties.
((jsx_attribute
  [(property_identifier) (jsx_namespace_name)] @injection.content)
  (#match? @injection.content "${attributes}")
  (#set! injection.language "datastar")
  (#set! injection.include-children))

; Attribute names in attrs={{ ... }} objects.
((jsx_attribute
  (property_identifier) @_name
  (jsx_expression
    (object
      (pair key: (string (string_fragment) @injection.content)))))
  (#eq? @_name "attrs")
  (#match? @injection.content "${attributes}")
  (#set! injection.language "datastar"))

; Expression values in attrs={{ ... }} objects.
((jsx_attribute
  (property_identifier) @_name
  (jsx_expression
    (object
      (pair
        key: (string (string_fragment) @_key)
        value: (string (string_fragment) @injection.content)))))
  (#eq? @_name "attrs")
  (#match? @_key "${expressions}")
  (#set! injection.language "datastar"))

((jsx_attribute
  (property_identifier) @_name
  (jsx_expression
    (object
      (pair
        key: (string (string_fragment) @_key)
        value: (string (string_fragment) @injection.content)))))
  (#eq? @_name "attrs")
  (#match? @_key "${media}")
  (#match? @injection.content ${quoted})
  (#set! injection.language "datastar"))
`;

for (const language of ["html", "templ", "jsx", "tsx"]) {
  output(
    `after/queries/${language}/injections.scm`,
    `; extends\n${header}${["html", "templ"].includes(language) ? html : jsx}`,
  );
}

// Helix host queries must not combine independent attribute expressions.
const standardHtml = `
((comment) @injection.content
 (#set! injection.language "comment"))

((script_element (raw_text) @injection.content)
 (#set! injection.language "javascript"))

((style_element (raw_text) @injection.content)
 (#set! injection.language "css"))
`;
output("docs/helix-html-injections.scm", header + standardHtml + html);
output(
  "queries/highlights-helix.scm",
  header + readFileSync(resolve(root, "queries/datastar/highlights.scm"), "utf8")
    .replaceAll("@variable.builtin.datastar", "@variable.builtin")
    .replaceAll("@function.builtin.datastar", "@function.builtin"),
);
